### ISSUE TITLE
Method loadDir of Class LOADSTYLE should be marked static

### ISSUE THREAD

**Issue by ernstblecha** [masakik/Aigaion#8]
In application/views/export/chooseformat.php on line 45 the method LOADSTYLE::loadDir(...) is called.
This results in a E_STRICT warning (PHP 5) on the "Select export format page".

Two possible solutions: 1) keep it compatible with stone-age PHP 4 and instantiate an object first
2) use the static keyword and hope everybody has their system up to date

**Comment by masakik** [comment]
Thankyou. I change function to static.
