### ISSUE TITLE
MySql database not created

### ISSUE THREAD

**Issue by SatinderpalSingh** [masakik/Aigaion#9]
After running the installation steps, nothing happened, only the blank screen. And no entry goes to the database.

**Comment by SatinderpalSingh** [comment]
The issue is with php7, it is running with php5 only

**Comment by masakik** [comment]
Hi, the framework used is quite old so it will not work in php7 because of mysql database driver.

**Comment by SatinderpalSingh** [comment]
Is there any development team working on the project to upgrade to php7. As it is running on php5 but have some user authentication issues. I am interesting in upgrading the project, is there any documentation available.

**Comment by masakik** [comment]
The original authors are not interested anymore and I have no time to work on this for a while. As far I can see mainly it needs to update codeigniter framework to make compatible with php7. I have no experience with codeigniter and the documentation is just the readme.md. I have used it some time ago but not using anymore. Any way I think it is a good piece of software and when I have more time I intend to keep maintaining. For a while if you could update to  make compatible with new version of php it is welcome.

**Comment by SatinderpalSingh** [comment]
Thank you, BTW i found some documentation at https://web.archive.org/web/20120608232424/http://www.aigaion.de:80/documentation

**Comment by masakik** [comment]
Very cool. Maybe we can put all the docs here. There is something at the wiki.
